### PR TITLE
Python script to generate man page

### LINKED ISSUE #830: [FEAT] More documentation in the Manpage
## Wanted features:

- Include all the available options, currently only a subset (compared to `fastfetch --help`) is actually listed.
- Include the information from running `fastfetch -h <option>` for all options.
- Explain/give examples of the structure of the config file, accepted values for options, how to change common things, etc.
- Include the JSON Schema found in the github wiki.

## Motivation:

When I want to read thorough documentation for a tool I look at the manpage (as many others might do). I expect to find more information in `man foo` than running `foo --help`. Right now, some of the info is available in the manpage, more is in `fastfetch --help` and other is in the github wiki.

Having all the documentation in the manpage would be beneficial because:

1. There would be a centralized place to look for the documentation, without needing to look at external resources or having to run multiple commands (running `fastfetch -h <option>` constantly is not very ergonomic).
2. Users can leverage the features of the program they use to read manpages to search for specific topics of their interest more easily.

### PR DESCRIPTION
**Pull request by Tiuxi**
Added the script `scripts/gen-man.py` that generate a man page using the `src/data/help.json` file, and print the generated file to stdout.

close #830

### CODE REVIEW

**Comment by CarterLi** [comment]
```
scripts/gen-man.py:146: SyntaxWarning: invalid escape sequence '\-'
  print(f"\-{ option['short'] }", end="")
scripts/gen-man.py:153: SyntaxWarning: invalid escape sequence '\-'
  print(f"\-\-{ option['long'] }", end="")
```

**Comment by CarterLi** [comment]
I'd like to keep the `Config Files` section in the old man file.

**Comment by CarterLi** [comment]
You can acquire the fastfetch version from `CMakeList.txt` using RegExp `^    VERSION (\d+\.\d+\.\d+)$`

**Comment by Tiuxi** [comment]
Is it relevant to also put a short example of a config file (E.g from a preset) at the end ?

**Comment by CarterLi** [comment]
Yes. You should also metion the Github Wiki page.

**Pull request merged**
