### PR TITLE
Make it possible to build without optional dependencies

### PR DESCRIPTION
**Pull request by CarterLi**
For users that don't uses a desktop environment, for example WSL and Ubuntu Server, don't force them installing unnecessary dependencies that they will never use to build this awesome program.

### CODE REVIEW

**Comment by LinusDierheimer** [comment]
I thought about something like this:

```c
#if !defined(__has_include) || __has_include("wayland-client.h")
    #include "wayland-client.h"
    //Wayland code
#else
    #warning Building without Wayland support, since the header was not found!
    //Fallback code
#endif
```

**Comment by LinusDierheimer** [comment]
Yea i just re read the documentation, seems like we have to use nested ifs: https://gcc.gnu.org/onlinedocs/gcc-10.1.0/cpp/_005f_005fhas_005finclude.html

**Comment by LinusDierheimer** [comment]
I didn't include the xfconf header, since i only need one line from it, which i just copied:
```c
typedef struct _XfconfChannel XfconfChannel; // /usr/include/xfce4/xfconf-0/xfconf/xfconf-channel.h#L39
```
I did that, because i thought requiring everybody to pull in the xfce ecosystem, for a feature only needed in xfce environments, is a bit unnecessary, considering i only need this one line. Now that we will have support to build without a feature, i think it is better to remove the line and include the header.

**Comment by LinusDierheimer** [comment]
Will you do the messages, or should i?

**Comment by CarterLi** [comment]
Screenshot_2021-10-20-01-13-34-375_com termux

Program stucked at ffPrintPackages. Details unknown

**Comment by CarterLi** [comment]
Suggestion: Can we arm a SIGINT handler to restore the cursor? Everytime I terminate the program with ^C the cursor disappear

**Pull request merged**
