### PR TITLE
Fix "AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras"

### LINKED ISSUE #859: [BUG] Camera module - AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras.
2024-05-04 00:29:26.160 fastfetch[32562:3328224] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.

Related to:

https://github.com/opencv/opencv-python/issues/916

https://developer.apple.com/documentation/avfoundation/avcapturedevicetypeexternalunknown

### PR DESCRIPTION
**Pull request by delneg**
Fixes #859

### CODE REVIEW

**Comment by CarterLi** [comment]
Hello. CI failed

**Review by xiaozhi12eigh — COMMENTED** [review]
src/detection/camera/camera_apple.m

**Comment by delneg** [comment]
> Hello. CI failed

Hello!
Thank you for taking a look.


It looks like CI is failing because of the old macOS 12 runner.

Github now has macOS 13 & macOS 14 runners, which should work with the new SDK - at least XCode 15 (according to https://developer.apple.com/support/xcode/)

https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md

https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md

**Comment by CarterLi** [comment]
We need to support old systems

**Comment by delneg** [comment]
> We need to support old systems, and homebrew enforces it

Ok, in that case, since XCode 15 can't be installed on macOS 12, this PR will have to be postponed, or I can close it if you want.

**Comment by pheiduck** [comment]
You have to implement a fallback.

**Pull request closed without merging**
