### PR TITLE
Add packages support for Gentoo Linux

### PR DESCRIPTION
**Pull request by ceamac**
Support for counting installed packages on Gentoo

Caveat: runs an external command, so maybe it would be better to add an ifdef (or not add the support at all).

### CODE REVIEW

**Comment by LinusDierheimer** [comment]
TBH i don't like to open a new process for this. Is it possible to implement emerge package count by using one of the counting functions in package.c?

**Comment by LinusDierheimer** [comment]
Much appreciated, thank you for your work!

**Comment by LinusDierheimer** [comment]
I rewrote some of your logic using the strbuf methods fastfetch has built in, can you please confirm that it still works?

**Comment by ceamac** [comment]
Yes, it still works.  Same result as before

**Comment by LinusDierheimer** [comment]
Great. Thank you again for figuring the logic out.

**Comment by SigHunter** [comment]
thank you very much for this, finally fastfetch is featurewise on par and I can switch from neofetch

**Pull request merged**
