### PR TITLE
feat: add zsh-completion

### PR DESCRIPTION
**Pull request by AtifChy**
#1197 

This pull request introduces completion for zsh. I've customized the python script originally used to generate fish shell completion to generate zsh completion.

### CODE REVIEW

**Comment by CarterLi** [comment]
How can I test it?

**Comment by AtifChy** [comment]
> How can I test it?

`fpath=(repos/fastfetch/completions $fpath)`

you may need to also run `autoload -Uz compinit && compinit`

then run `fastfetch <TAB>`

**Comment by CarterLi** [comment]
* `_fastfetch` should be renamed to `fastfetch.zsh`
* This file should be installed by cmake. See https://github.com/fastfetch-cli/fastfetch/blob/dev/CMakeLists.txt#L1340-L1344

**Comment by AtifChy** [comment]
> * `_fastfetch` should be renamed to `fastfetch.zsh`
but this is how zsh completion files are named

**Comment by CarterLi** [comment]
The file can be renamed when installing

**Comment by AtifChy** [comment]
> * This file should be installed by cmake. See https://github.com/fastfetch-cli/fastfetch/blob/dev/CMakeLists.txt#L1340-L1344

done

**Comment by CarterLi** [comment]
Thanks

**Pull request merged**
