### PR TITLE
prioritize lscpu model output for arm linux systems if available

### PR DESCRIPTION
**Pull request by theofficialgman**
resolves https://github.com/fastfetch-cli/fastfetch/issues/567#issuecomment-2183677298

### CODE REVIEW

**Comment by CarterLi** [comment]
It's not fallback. It's force.

lscpu should always used as fallback, because you cant assume it's available.

**Comment by theofficialgman** [comment]
> It's not fallback. It's force.
> 
> lscpu should always used as fallback, because you cant assume it's available.

corrected name.

feel free to rework so that the lscpu section is called first so that it takes priority rather than forcing it.

**Comment by theofficialgman** [comment]
@CarterLi how about something like that ^
Now lscpu is only prioritized and will fallback to /proc/cpuinfo if lscpu is not available

**Comment by CarterLi** [comment]
I dont like the idea. The CPU name was reported by Linux kernel. If you think it is wrong, it is a kernel issue.

**Comment by theofficialgman** [comment]
> I dont like the idea. The CPU name was reported by Linux kernel. If you think it is wrong, it is a kernel issue.

its not an issue. same deal with apple silicon which you have codepaths for. this is just how ARM cpu's have always been represented (with their implementer, architecture, variant, and part numbers) with no "pretty" model name

https://github.com/util-linux/util-linux/blob/master/sys-utils/lscpu-arm.c

**Comment by theofficialgman** [comment]
also with this you can remove the hacky asahi codepaths

**Comment by theofficialgman** [comment]
https://github.com/util-linux/util-linux/commit/744d62ee0c54963539832ec5943f3d25e0fccfbd

image

so yeah sorry not going to happen. just use lscpu like everyone else

**Comment by CarterLi** [comment]
Won't fix

**Pull request closed without merging**
