### PR TITLE
feat: Support Moore Threads GPU

### PR DESCRIPTION
**Pull request by yeahdongcn**
Testing done:

```bash
❯ ./fastfetch --gpu-driver-specific
                            ....
              .',:clooo:  .:looooo:.           xiaodongye@xiaodongye-s80
           .;looooooooc  .oooooooooo'          -------------------------
        .;looooool:,''.  :ooooooooooc          OS: Ubuntu focal 20.04 x86_64
       ;looool;.         'oooooooooo,          Kernel: Linux 5.4.0-42-generic
      ;clool'             .cooooooc.  ,,       Uptime: 17 days, 21 hours, 8 mins
         ...                ......  .:oo,      Packages: 1838 (dpkg), 45 (nix-user), 9 (snap)
  .;clol:,.                        .loooo'     Shell: zsh 5.8
 :ooooooooo,                        'ooool     Display (Virtual-1): 1920x1080
'ooooooooooo.                        loooo.    Terminal: node
'ooooooooool                         coooo.    CPU: 12th Gen Intel(R) Core(TM) i5-12400 (12) @ 4.40 GHz
 ,loooooooc.                        .loooo.    GPU: Moore Threads MTT S80 @ 1.80 GHz (11.62 MiB / 16.00 GiB, 0%) [Discrete]
   .,;;;'.                          ;ooooc     Memory: 4.97 GiB / 31.11 GiB (16%)
       ...                         ,ooool.     Swap: 51.26 MiB / 976.00 MiB (5%)
    .cooooc.              ..',,'.  .cooo.      Disk (/): 865.21 GiB / 914.46 GiB (95%) - ext4
      ;ooooo:.           ;oooooooc.  :l.       Local IP (enp5s0): 192.168.4.137/23
       .coooooc,..      coooooooooo.           Locale: en_US.UTF-8
         .:ooooooolc:. .ooooooooooo'
           .':loooooo;  ,oooooooooc                                    
               ..';::c'  .;loooo:'                                     

❯ ./fastfetch --gpu-temp
                            ....
              .',:clooo:  .:looooo:.
           .;looooooooc  .oooooooooo'          xiaodongye@xiaodongye-s80
        .;looooool:,''.  :ooooooooooc          -------------------------
       ;looool;.         'oooooooooo,          OS: Ubuntu focal 20.04 x86_64
      ;clool'             .cooooooc.  ,,       Kernel: Linux 5.4.0-42-generic
         ...                ......  .:oo,      Uptime: 17 days, 20 hours, 52 mins
  .;clol:,.                        .loooo'     Packages: 1838 (dpkg), 45 (nix-user), 9 (snap)
 :ooooooooo,                        'ooool     Shell: zsh 5.8
'ooooooooooo.                        loooo.    Display (Virtual-1): 1920x1080
'ooooooooool                         coooo.    Terminal: node
 ,loooooooc.                        .loooo.    CPU: 12th Gen Intel(R) Core(TM) i5-12400 (12) @ 4.40 GHz
   .,;;;'.                          ;ooooc     GPU: Moore Threads MTT S80 - 56.0°C [Discrete]
       ...                         ,ooool.     Memory: 4.78 GiB / 31.11 GiB (15%)
    .cooooc.              ..',,'.  .cooo.      Swap: 51.26 MiB / 976.00 MiB (5%)
      ;ooooo:.           ;oooooooc.  :l.       Disk (/): 865.20 GiB / 914.46 GiB (95%) - ext4
       .coooooc,..      coooooooooo.           Local IP (enp5s0): 192.168.4.137/23
         .:ooooooolc:. .ooooooooooo'           Locale: en_US.UTF-8
           .':loooooo;  ,oooooooooc
               ..';::c'  .;loooo:'                                     
                                                                       
```

### CODE REVIEW

**Comment by CarterLi** [comment]
Is 0.00 GHz desired? Does `--gpu-temp` work?

**Comment by yeahdongcn** [comment]
> Is 0.00 GHz desired? Does `--gpu-temp` work?

`--gpu-temp` works fine:
```bash
GPU: Moore Threads Device 0201 (VGA compatible) - 56.0°C [Discrete]
```

Let me check the `0.00 GHz`.

**Comment by CarterLi** [comment]
Please also check if `/usr/share/hwdata/pci.ids` contains the MT GPU model you use. If not, you may want to manually update it.

image

**Comment by yeahdongcn** [comment]
OK. Just replace the file from https://pci-ids.ucw.cz/, correct?

**Comment by CarterLi** [comment]
yeah

**Comment by CarterLi** [comment]
I have added `FFGpuDriverResult::name` in case users' `pci.ids` doesn't contain their GPU models. Please do if for MT too

**Comment by yeahdongcn** [comment]
> I have added `FFGpuDriverResult::name` in case users' `pci.ids` doesn't contain their GPU models. Please do if for MT too

Done.

**Comment by CarterLi** [comment]
Good. I'll do some cleanups and port the code to Windows. It would be helpful if you can find someone to test it

**Comment by CarterLi** [comment]
I assume the dll name is `mtml.dll` right?

**Comment by CarterLi** [comment]
Can you test this? https://github.com/fastfetch-cli/fastfetch/commit/1a66bc4ec0dee43a30f26c0db11cc65a0fc9bec7

**Comment by yeahdongcn** [comment]
> Can you test this? [1a66bc4](https://github.com/fastfetch-cli/fastfetch/commit/1a66bc4ec0dee43a30f26c0db11cc65a0fc9bec7)

Works well on Linux.

**Comment by yeahdongcn** [comment]
But I'm afraid MTGPU drivers haven't officially announced it supports BSD.

**Comment by yeahdongcn** [comment]
> I assume the dll name is `mtml.dll` right?

Yes (just confirmed internally).

**Comment by CarterLi** [comment]
祝国产越来越好！

**Comment by yeahdongcn** [comment]
> Can you test this? [1a66bc4](https://github.com/fastfetch-cli/fastfetch/commit/1a66bc4ec0dee43a30f26c0db11cc65a0fc9bec7)

Screenshot 2024-08-02 at 17 27 54

Also looks good on Windows!

**Comment by CarterLi** [comment]
> > Can you test this? [1a66bc4](https://github.com/fastfetch-cli/fastfetch/commit/1a66bc4ec0dee43a30f26c0db11cc65a0fc9bec7)
> 
> Screenshot 2024-08-02 at 17 27 54
> 
> Also looks good on Windows!

You must specify --gu-driver-specific to let fastfetch call gpu driver

**Comment by yeahdongcn** [comment]
> > > Can you test this? [1a66bc4](https://github.com/fastfetch-cli/fastfetch/commit/1a66bc4ec0dee43a30f26c0db11cc65a0fc9bec7)
> > 
> > 
> > Screenshot 2024-08-02 at 17 27 54
> > Also looks good on Windows!
> 
> You must specify --gpu-driver-specific to let fastfetch call gpu driver

Screenshot 2024-08-02 at 17 57 22

A segmentation fault occurs at the end.

**Comment by CarterLi** [comment]
What if you remove the atexit?

**Comment by yeahdongcn** [comment]
> What if you remove the atexit?

Screenshot 2024-08-02 at 18 10 59

I opened a JIRA internally.

**Comment by CarterLi** [comment]
Nice

**Comment by CarterLi** [comment]
Wait. Unlike `nvmlShutdown`, `mtmlLibraryShutDown` requires a parameter `MtmlLibrary *lib`

**Comment by CarterLi** [comment]
https://github.com/fastfetch-cli/fastfetch/commit/a856350416b37cbd9820f04d4165e17b8a775ed9

**Comment by yeahdongcn** [comment]
> [a856350](https://github.com/fastfetch-cli/fastfetch/commit/a856350416b37cbd9820f04d4165e17b8a775ed9)

My bad. Thanks for fixing this.

**Pull request merged**
