### PR TITLE
CI: add Winget Releaser workflow

### PR DESCRIPTION
**Pull request by sitiom**
- Continuation of https://github.com/fastfetch-cli/fastfetch/issues/320#issuecomment-1404822340

[This action](https://github.com/vedantmgoyal2009/winget-releaser) automatically generates manifests for Winget Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Fastfetch has been added to Winget (https://github.com/microsoft/winget-pkgs/pull/154718), and this workflow will be used to update it.

**Before merging this:**
1. Add a **classic** PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN`.

example

2. Fork https://github.com/microsoft/winget-pkgs under @fastfetch-cli. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Install [Pull](https://github.com/apps/pull) on the winget-pkgs fork to ensure that it is constantly updated.

If you want to see an example of a PR created using this action, see [microsoft/winget-pkgs/pulls (Pull request has been created with WinGet Releaser)](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+Pull+request+has+been+created+with+WinGet+Releaser).

### CODE REVIEW

**Comment by CarterLi** [comment]
@LinusDierheimer I don't have the permission. Can you help with this?

**Comment by sitiom** [comment]
The `fork-user` can be set to your account instead if that's what you want

**Comment by sitiom** [comment]
I noticed that `fastfetch-windows-aarch64.zip` is being put manually in the releases; that would be a problem for this action which expects all assets to be available on release.

**Comment by CarterLi** [comment]
Yeah. I didn't find a way to build windows-aarch64 with Github Actions.

**Comment by Get-Newsletters-Int** [comment]
@LinusDierheimer

**Comment by LinusDierheimer** [comment]
@CarterLi Made you an admin, does it work now?

**Comment by sitiom** [comment]
> Yeah. I haven't found a way to build windows-aarch64 binaries with Github Actions.

Perhaps I should add a `workflow_dispatch` trigger so that you can run it manually.

**Comment by CarterLi** [comment]
I'm happy with current situation. Closing

**Comment by sitiom** [comment]
Whats situation?

**Pull request closed without merging**
