### PR TITLE
Added "Furreto Linux" support

### PR DESCRIPTION
**Pull request by FurretDev**
linux distribution still in development yeah
image

### CODE REVIEW

**Comment by CarterLi** [comment]
The logo file seems unpolished. 13KiB size for one logo seems unacceptable to me. Please remove duplicated colors and convert ANSI escape code to `$N`

**Comment by FurretDev** [comment]
this is actually what i was afraid of, i'll try to do something then

**Comment by FurretDev** [comment]
tried making the logo less than 13 KiB, it's 5,8 KiB now, even though the logo lost some of its quality but eh i guess that is fair, although i've seen a logo with like 3,6 KiB, 2 KiB difference lol

**Comment by CarterLi** [comment]
Please merge the duplicate color tags

For example

```
${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5} ${c5}
```

Should be

```
${c5}        (whitespace * N)
```

**Comment by FurretDev** [comment]
Got it, I'll fix the issues once I get back home

*I actually made this with a script that turned jp2a into something that actually worked in neofetch, silly me.*

**Comment by FurretDev** [comment]
i think this is it, the logo is now at 1,1KiB
i wish i could've made it like the first image but i mean i'm pretty ok with this result
image

**Comment by FabioLolix** [comment]
Hello @FurretDev, where is developed and where can be downloaded this distro?

**Comment by cyklusiguess** [comment]
i use this distro

not giving download

**Comment by FurretDev** [comment]
i can confirm he is indeed using this distro

**Pull request merged**
