### PR TITLE
Update builtin.c

### PR DESCRIPTION
**Pull request by Princess-Sunset-Shimmer**
is this correct?
( and i didn't find "logo_builtin.h" file, where is it? )

### CODE REVIEW

**Comment by CarterLi** [comment]
I just updated it myself.

**Comment by CarterLi** [comment]
Would you like to show the config file you use?

**Comment by Princess-Sunset-Shimmer** [comment]
Thanks for your update, and yes SURE, of course i'd very appreciate to share my Config-File

**Comment by Princess-Sunset-Shimmer** [comment]
here i copied for you
```jsonc
{
"logo": {
    "source": "arch",
    "color": {"1": "red", "2": "yellow"}
    },
"display": {
    "color": {"separator": "blue", "output": "white"},
    "separator": " | "
    },
"modules": [ 
    {"type": "kernel", "key": " /\\rch Linux", "keyColor": "magenta"},
    {"type": "custom", "format": ">-----------<+>----------------------------------<", "outputColor": "blue"},
    {"type": "uptime", "key": "   Uptime   ", "keyColor": "green"},
    {"type": "shell", "key": "   Shell    ", "keyColor": "green"},
    {"type": "terminal", "key": "   Terminal ", "keyColor": "green"},
    {"type": "terminalfont", "key": "   Font     ", "keyColor": "green"},
    {"type": "packages", "key": "   Packages ", "keyColor": "green"},
    {"type": "localip", "key": "   Local IP ", "keyColor": "green"},
    {"type": "custom", "format": ">-----------<+>----------------------------------<", "outputColor": "blue"},
    {"type": "display", "key": "   Display  ", "keyColor": "cyan"},
    {"type": "cpu", "key": "   CPU      ", "keyColor": "cyan"},
    {"type": "gpu", "key": "   GPU      ", "keyColor": "cyan"},
    {"type": "memory", "key": "   RAM      ", "keyColor": "cyan"},
    {"type": "swap", "key": "   SWAP     ", "keyColor": "cyan"},
    {"type": "disk", "key": "   Disk     ", "keyColor": "cyan"},
    {"type": "battery", "key": "   Battery  ", "keyColor": "cyan"},
    {"type": "custom", "format": ">-----------<+>----------------------------------<", "outputColor": "blue"},
    "break",
    {"type":"colors", "paddingLeft": 9}
    ]
}
```

**Comment by CarterLi** [comment]
Did a little cleanup

https://github.com/fastfetch-cli/fastfetch/blob/dev/presets/examples/22.jsonc

**Comment by Princess-Sunset-Shimmer** [comment]
Whoa, that's Amazing
And very Thanks for you selected my-config as official-example
( i'am so Happy that i may see the change sooner in next Arch Linux package update )
image

**Comment by Princess-Sunset-Shimmer** [comment]
i see it, i just updated my Arch Linux now, and So thanks to you that i can directly use **arch3** as official-builtin-logo right now

**Pull request closed without merging**
