### PR TITLE
refactor: Improve memory metric parsing

### PR DESCRIPTION
**Pull request by nnyyxxxx**

### CODE REVIEW

**Comment by CarterLi** [comment]
Can you clarify what is **improved**?

**Comment by nnyyxxxx** [comment]
> Can you clarify what is **improved**?

this version uses a for-loop instead of multiple conditional checks

and other minor tweaks

**Comment by CarterLi** [comment]
No. You made it slower. If `MemAvailable` is available, other properties should not be searched.

**Comment by nnyyxxxx** [comment]
> No. You made it slower. If `MemAvailable` is available, other properties should not be searched.

would you like me to fix that :upside_down_face:

**Comment by CarterLi** [comment]
No

**Pull request closed without merging**
