### PR TITLE
fix(DiskIO): fix readlink

### PR DESCRIPTION
**Pull request by apocelipes**

### CODE REVIEW

**Comment by CarterLi** [comment]
You fix what?

**Comment by apocelipes** [comment]
`char pathSysDeviceReal[PATH_MAX] = "";`

equals to

`char pathSysDeviceReal[PATH_MAX] = { '\0' };`

and the manpages said: 
> readlink() does not append a null byte to buf.

So, if readlink success, we got a invalid Null-terminated string.

**Comment by apocelipes** [comment]
Or, if use this:

`char pathSysDeviceReal[PATH_MAX] = { '\0' };`

It will zero-filled by memset or other functions. Since PATH_MAX on some Linux distros are set to 4096, it could be a noticeable cost.

**Comment by CarterLi** [comment]
image

In <https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1124.pdf>, Page 127

**Comment by apocelipes** [comment]
> image
> 
> In https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1124.pdf, Page 127

This since C11, this project using C11, so, it will be zero-filled, and in most cases it's unnecessary.

**Comment by CarterLi** [comment]
> This since C11

Citation needed

**Comment by CarterLi** [comment]
And even if you want to "fix" this, the same code in physical_linux.c (committed today) should be fixed too.

**Comment by CarterLi** [comment]
Please be cautious when using words like "bug" and "fix"

**Comment by apocelipes** [comment]
> > This since C11
> 
> Citation needed

It's my miss, C99 said the same thing at 6.7.8-21, some old unix's CCs confuse me with their implement behaviors.

**Comment by apocelipes** [comment]
> Please be cautious when using words like "bug" and "fix"

Thank u, I see.

**Pull request merged**
